### ISSUE TITLE
[Question] Server update strategies - best-effort

### ISSUE THREAD

**Issue by oliviervaussy** [coreos/update_engine#58]
Hi,

I have a quick question regarding the update strategy :

I have 2 servers in my fleet : Server A and Server B
Each of them runs 1 service : Service 1

When A decides to reboot using the best-effort strategy, it takes the lock and reboot, then service 1 needs to start. Does A unlock the lock only when service 1 (which is registered in systemd) is 'started' or is it possible that Server B reboot while Service 1 is still trying to start (it can take a while to docker pull the image or the start could fail for whatever reason) ?

Do we have any control on that ?

Thanks

**Comment by crawford** [comment]
This issue was moved to coreos/bugs#257
