### ISSUE TITLE
Feature request: Specify a version to update to

### ISSUE THREAD

**Issue by scejrussell** [coreos/update_engine#80]
In order to reproduce an environment at a specific version of CoreOS for stability / debugging purposes, it is currently necessary to upload the base image @ that version into our image store (OpenStack Glance, ESX, etc). Due to the security setup of our environment, this is a prohibitively difficult and expensive task that involves many manual steps.

If the update_engine_client could be given a parameter `--update-to=XXX.X.X`, then we could boot from older images and use the cloud-config file to direct update_engine to download a specific CoreOS version.

**Comment by utyagi24** [comment]
I second this feature request. To be able to specify a version number for update is required in deployments where a specific update needs to be selected based on compatibility with the Docker, etcd and other software packaged in that particular update.

**Comment by crawford** [comment]
@utyagi24 assuming you are using the daemons provided with the OS, you can be sure that they are compatible with one another. That portion of the OS is updated atomically.

**Comment by crawford** [comment]
When update engine grabs an update from the server, the client is not the one to determine which version gets downloaded. The server tells the client where to find the update payload and it's version. Reversing this role would require significant changes to the Omaha protocol, invalidating any security vetting done up to this point. It's just not feasible for us to make this change.

If control is truly needed over the exact version of CoreOS your cluster is running, it's a heck of a lot easier and more powerful to use [CoreUpdate](https://coreos.com/products/).

**Comment by utyagi24** [comment]
@crawford My applications use Docker remote API, depend on etcd API etc.  With any CoreOS update all these API version are subject to change and many enterprise applications demanding high reliability are not going to be comfortable with shifting grounds underneath.

**Comment by crawford** [comment]
@utyagi24 I see. Then in that case, [CoreUpdate](https://coreos.com/products/) is essential.
